apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibitoye-front
  namespace: monsters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibitoye-front
  template:
    metadata:
      labels:
        app: ibitoye-front
    spec:
      containers:
      - image: ${FRONT_IMAGE_NAME}
        imagePullPolicy: Always
        name: ibitoye-front
        envFrom:
        - configMapRef:
            name: ibitoye
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibitoye-back
  namespace: monsters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibitoye-back
  template:
    metadata:
      labels:
        app: ibitoye-back
    spec:
      containers:
      - image: ${BACK_IMAGE_NAME}
        imagePullPolicy: Always
        name: ibitoye-back
        envFrom:
        - configMapRef:
            name: ibitoye
